const GAME_ROUNDS = 3;
const OPERATION_ADD = '+';
const OPERATION_SUB = '-';
const OPERATION_MUL = '*';
const PROGRESSION_LEN = 10;

export {
  GAME_ROUNDS,
  OPERATION_ADD,
  OPERATION_SUB,
  OPERATION_MUL,
  PROGRESSION_LEN,
};
